"""Step 3 — Production Workshop Models."""

from pydantic import BaseModel, Field


class VisualStyleGuide(BaseModel):
    """Defines the visual DNA of the entire ad — generated by the Worker Director."""

    color_palette: list[str] = Field(
        description="Array of hex colors defining the ad's palette (not the brand palette — the ad's mood palette)"
    )
    lighting_style: str = Field(
        description="Lighting direction (e.g. 'golden hour backlight', 'neon-lit noir', 'soft diffused studio')"
    )
    camera_style: str = Field(
        description="Camera approach (e.g. 'handheld documentary', 'steadicam tracking', 'static wide shots')"
    )
    grain_texture: str = Field(
        description="Film grain/texture feel (e.g. 'clean digital', '35mm film grain', 'grainy 16mm')"
    )
    art_direction: str = Field(
        description="Overall art direction summary in 1-2 sentences"
    )
    format_ratio: str = Field(
        default="16:9",
        description="Aspect ratio for the ad (e.g. '16:9', '9:16', '1:1')",
    )
    visual_keywords: list[str] = Field(
        description="Array of visual keywords that define the look (e.g. ['cinematic', 'desaturated', 'warm shadows'])"
    )


class EnrichedScene(BaseModel):
    """An enriched version of a master sequence scene — includes visual direction for image generation."""

    scene_number: int = Field(description="Scene number (1-6)")
    beat_name: str = Field(description="Name of the emotional beat")
    emotion: str = Field(description="Emotion(s) for this scene")
    action_summary: str = Field(description="1 sentence — what happens emotionally")
    duration_estimate: str = Field(description="Timecode range (e.g. '0:00–0:05')")
    visual_description: str = Field(
        description="Detailed visual description for image generation — what the camera sees"
    )
    camera_direction: str = Field(
        description="Camera movement and framing (e.g. 'close-up tracking left', 'wide establishing shot')"
    )
    lighting_mood: str = Field(
        description="Scene-specific lighting (e.g. 'harsh overhead spotlight', 'golden hour warmth')"
    )
    setting_description: str = Field(
        description="Where the scene takes place (e.g. 'rooftop at dusk, city skyline behind')"
    )
    product_placement: str = Field(
        default="",
        description="How the product appears in this scene (e.g. 'hero shot on table', 'held by talent', 'not visible')",
    )


class SceneKeyframes(BaseModel):
    """Tracks the generated keyframes for one scene."""

    scene_number: int = Field(description="Scene number (1-6)")
    keyframe_start_uri: str = Field(
        default="", description="GCS URI of the start-of-scene keyframe image"
    )
    keyframe_end_uri: str = Field(
        default="", description="GCS URI of the end-of-scene keyframe image"
    )
    prompt_start: str = Field(
        default="", description="Prompt used to generate the start keyframe"
    )
    prompt_end: str = Field(
        default="", description="Prompt used to generate the end keyframe"
    )
    scene_locked: bool = Field(
        default=False, description="Whether the scene has been validated"
    )
